version: '3'

services:
  memcached:
    container_name: memcached
    image: memcached:1.5
    ports:
        - 11211:11211
  php:
    container_name: php
    build: ./php
    #image: php:7.3-fpm-alpine
    restart: always
    volumes:
        - ./webroot:/var/www/html
#        - ./php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - 8080:80
